
name: run bdayscript1.py

on:
  schedule:
    - cron: '50 9 * * *' # Runs daily at 1 am UTC

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12 # Specify the Python version you want to use

      - name: Install dependencies
        run: pip install openpyxl requests

      - name: Run Python Script
        run: python bdayscript1.py
