name: run bdayscript1.py

on:
  schedule:
    - cron: '40 2 * * *' # Runs daily at 1 am UTC
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12' # Replace with your Python version

      name: install python pakcages
      run: |
        python =m pip install --upgrade pip
        pip install =r requirements.txt

    - name: Run Python Script
      run: python bdayscript1.py

